// Copyright 2014 Volker Dobler.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"flag"
	"log"
	"os"

	"github.com/vdobler/ht/ht"
)

var cmdRun = &Command{
	RunTests:    runRun,
	Usage:       "run <test>...",
	Description: "run a single test",
	Flag:        flag.NewFlagSet("run", flag.ContinueOnError),
	Help: `
Run loads the single test, unrolls it and prepares it and executes the
test (or the first of the unroled tests).
Variables set with the -D flag overwrite variables read from file with -Dfile.
	`,
}

func init() {
	addVariablesFlag(cmdRun.Flag)
	addDfileFlag(cmdRun.Flag)
	addVerbosityFlag(cmdRun.Flag)
	addSeedFlag(cmdRun.Flag)
	addOutputFlag(cmdRun.Flag)
	addSkiptlsverifyFlag(cmdRun.Flag)
}

func runRun(cmd *Command, tests []*ht.Test) {
	logger := log.New(os.Stdout, "", log.LstdFlags)
	suite := &ht.Suite{
		Name: "Autogenerated suite for run",
		Log:  logger,
	}

	suite.Tests = tests
	err := suite.Prepare()
	if err != nil {
		log.Println(err.Error())
		os.Exit(3)
	}
	if verbosity != -99 {
		for i := range suite.Tests {
			suite.Tests[i].Verbosity = verbosity
		}
	}
	suite.Variables = variablesFlag
	runExecute(cmd, []*ht.Suite{suite})
}
